######################
# Stage: Builder
FROM --platform=linux/amd64 ruby:3.0.1 as Builder
#RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs libxml2
RUN apt-get update -qq && apt-get install -y build-essential nodejs libxml2

RUN mkdir -p /app
RUN mkdir -p /app/tmp
WORKDIR /app

# Install gems
ADD Gemfile* /app/
RUN gem install bundler --version=2.3.1
RUN bundle config --global frozen 1 \
  && bundle install --without development test --retry 3 \
  # Remove unneeded files (cached *.gem, *.o, *.c)
  && rm -rf /usr/local/bundle/cache/*.gem \
  && find /usr/local/bundle/gems/ -name "*.c" -delete \
  && find /usr/local/bundle/gems/ -name "*.o" -delete

# Install yarn packages
#COPY package.json /app/
#RUN yarn install

ADD . /app

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_KEY
ARG S3_ASSET_REGION
ARG S3_ASSET_BUCKET
ARG SECRET_KEY_BASE

RUN RAILS_ENV=staging \
  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  AWS_SECRET_KEY=$AWS_SECRET_KEY \
  S3_ASSET_REGION=$S3_ASSET_REGION \
  S3_ASSET_BUCKET=$S3_ASSET_BUCKET \
  SECRET_KEY_BASE=$SECRET_KEY_BASE \
  bundle exec rake assets:precompile

# Remove files/folders not needed in resulting image
RUN rm -rf tmp/cache test public/robots.txt-staging public/robots.txt-staging-temp

###############################
# Stage Final
FROM --platform=linux/amd64 ruby:3.0.1
LABEL maintainer="Duc T. Lam <dlam@naturesflavors.com>"

# Copy app with gems from former build stage
COPY --from=Builder /usr/local/bundle/ /usr/local/bundle/
COPY --from=Builder --chown=app:app /app /app

WORKDIR /app

# Save timestamp of image building
RUN date -u > BUILD_TIME

# Start up
CMD ["bundle", "exec", "sidekiq", "-d", "-q", "default", "-q", "mailers", "-L", "./log/sidekiq.log"]
