######################
# Stage: Builder
FROM --platform=linux/amd64 ruby:3.0.1 as Builder
RUN apt-get update -qq && apt-get install -y build-essential nodejs libxml2

RUN mkdir -p /app
RUN mkdir -p /app/tmp
WORKDIR /app

# Install gems
ADD Gemfile* /app/
RUN gem install bundler --version=2.3.1
RUN bundle config --global frozen 1 \
  && bundle install --without development test --retry 3 \
  # Remove unneeded files (cached *.gem, *.o, *.c)
  && rm -rf /usr/local/bundle/cache/*.gem \
  && find /usr/local/bundle/gems/ -name "*.c" -delete \
  && find /usr/local/bundle/gems/ -name "*.o" -delete

ADD . /app

# Remove files/folders not needed in resulting image
RUN rm -rf .env* .set-build* tmp/cache test public/robots.txt-staging public/robots.txt-staging-temp

###############################
# Stage Final
FROM --platform=linux/amd64 ruby:3.0.1
LABEL maintainer="Duc T. Lam <dlam@naturesflavors.com>"

# Copy app with gems from former build stage
COPY --from=Builder /usr/local/bundle/ /usr/local/bundle/
COPY --from=Builder --chown=app:app /app /app

WORKDIR /app

# Save timestamp of image building
RUN date -u > BUILD_TIME

# Start up
CMD ["bundle", "exec", "sidekiq", "-d", "-q", "default", "-q", "mailers"]
