Generate product feed to AWS S3 every night at 2 AM:
  cron: "0 2 * * *"
  class: "GenerateProductFeedWorkerAwsS3"
  queue: default

Refresh sitemap at 12:00 AM:
  cron: "0 0 * * *"
  class: "SitemapRefreshWorker"
  queue: default

Generate Doofinder feed to AWS S3 at 12:30 AM:
  cron: "30 0 * * *"
  class: "DoofinderFeedWorkerAwsS3"
  queue: default

Doofinder cache worker at 1:30 AM:
  cron: "30 1 * * *"
  class: "DoofinderCacheWorker"
  queue: default

YotPo cache worker at 1:00 AM:
  cron: "0 1 * * *"
  class: "YotpoCacheWorker"
  queue: default