Refresh sitemap at 12:00 AM:
  cron: "0 0 * * *"
  class: "SitemapRefreshWorker"
  queue: default

Generate Doofinder feed to AWS S3 at 12:30 AM:
  cron: "30 0 * * *"
  class: "DoofinderFeedWorkerAwsS3"
  queue: default

YotPo cache worker at 1:00 AM:
  cron: "0 1 * * *"
  class: "YotpoCacheWorker"
  queue: default

Generate product feed to AWS S3 every night at 2 AM:
  cron: "0 2 * * *"
  class: "GenerateProductFeedWorkerAwsS3"
  queue: default

Data cache worker at 3:00 AM:
  cron: "0 3 * * *"
  class: "DataCacheWorker"
  queue: default

Generate YotPo feed to AWS S3 every night at 4 AM:
  cron: "0 4 * * *"
  class: "YotpoFeedWorkerAwsS3"
  queue: default
