:verbose: false
:concurrency: 5
:timeout: 25
:max_retries: 10

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - mailers
  - default

# you can override concurrency based on environment
production:
  :concurrency: 10
staging:
  :concurrency: 5